// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vedxvhmdigtwfqqpyejl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZHh2aG1kaWd0d2ZxcXB5ZWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTg2NDEsImV4cCI6MjA2MDkzNDY0MX0.AyTu8zbqPc7IAf1MDeb-xPC6O6ggGg2ZSrhzq_4Had4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);